#! /bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: $(basename $0) <num>"
    exit 1
fi

rep="day$1"
mkdir $rep
cd $rep
go mod init $rep 2> /dev/null
touch sample.txt input.txt
cat > main.go << FIN 
package main

import _ "embed"

func main() {
}
FIN
cd ..
exit 0
